name: nats-publish
description: Publishes a message to a NATS subject
author: Operation Spark
inputs:
  subject:
    description: The subject to publish to
    required: true
  message:
    description: The message to publish
    required: true
    default: '{}'
  urls:
    description: The NATS server URLs
    required: true
  jwt:
    description: The JWT to use for authentication
    required: false
  nKeySeed:
    description: The NKey seed to use to sign the JWT
    required: false

outputs:
  published:
    description: The published message
runs:
  using: node20
  main: dist/index.js
